services:
  db:
    networks:
      - internal
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=${DB_HOST:?}
      - POSTGRES_USER=${DB_USER:?}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?}
      - POSTGRES_NAME=${DB_NAME:?}

  api:
    networks:
      - internal
    build: .
    # command: ./init.sh
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: .
          target: /code
    env_file:
      - ./.env
    depends_on:
      - db

  celery:
    networks:
      - internal
    build: .
    command: celery --app=core worker --loglevel=info
    volumes:
      - celery:/data
    env_file:
      - ./.env
    environment:
      - CELERY_BROKER=${REDIS_URL:?}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:?}
    depends_on:
      - api
      - redis

  redis:
    networks:
      - internal
    image: redis

volumes:
  db:
  celery:

networks:
  internal:
