services:
  db:
    networks:
      - internal
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_NAME=${DB_NAME:?}
      - POSTGRES_USER=${DB_USER:?}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?}

  drf:
    networks:
      - internal
    build: .
    command: ./init.sh
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  db:

networks:
  internal:
