# Generated by Django 5.0.3 on 2024-03-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="task_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
