# Generated by Django 4.2.18 on 2025-02-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_journalentry_journalentryline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["order", "created_at"]},
        ),
        migrations.AddField(
            model_name="account",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="accountsubtype",
            name="type",
            field=models.CharField(
                choices=[
                    ("asset", "Asset"),
                    ("liability", "Liability"),
                    ("equity", "Equity"),
                    ("income", "Income"),
                    ("expense", "Expense"),
                ],
                max_length=10,
            ),
        ),
    ]
