# Generated by Django 5.0.3 on 2024-03-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("number", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name_plural": "Taxes",
            },
        ),
    ]
